/* ----------------------------------------------------------------------------
 * @copyright (C) 2018, Alert Logic, Inc
 * @doc
 * 
 * The purpose of this function is to process dead letter blobs generated by 
 * EhubGeneral function.
 * Dead letter blobs are located in 'alertlogic-dl' container located in the
 * web application storage account.
 * 
 * @end
 * ----------------------------------------------------------------------------
 */

const AlAzureDlBlob = require('@alertlogic/al-azure-collector-js').AlAzureDlBlob;
const ehubCollector = require('../common/ehub_collector');
const ehubGeneralFormat = require('../EHubGeneral/format').logRecord;
const invocations = require('../common/invocations');
const MAX_AMOUNT_OF_DL_MESSAGES = 3;

function getCollectorFunName(blobName) {
    return blobName.split('/')[1];
}

const processErrorFun = function(context, err, messages) {
    context.log.error('Error processing batch:', err);
    const skipped = messages.records ? messages.records.length : messages.length;
    return skipped;
};

async function processBlob(context, blob, dlblobText) {
    try {
        let formatFun;
        switch(getCollectorFunName(blob.name)) {
            case 'ehubgeneral':
                formatFun = ehubGeneralFormat;
                break;
            default:
                formatFun = ehubGeneralFormat;
                break;
        }
        
        const dlBlobMessages = getDlBlobMessages(dlblobText);

        const result = await ehubCollector(context, dlBlobMessages, formatFun, processErrorFun);
        
        if (result.skipped) {
            throw new Error(`Unprocessed records: ${result.skipped}`);
        }
        
        return result;
    } catch (error) {
        context.log.error(`Error processing DL blob ${blob.name}:`, error);
        throw error;
    }
}

function getDlBlobMessages(dlblobText) {
    const parsedBlob = JSON.parse(dlblobText);

    if (Array.isArray(parsedBlob) && parsedBlob[0].errorSample) {
        const blobMessages = parsedBlob[0].messages;
        if (blobMessages.length <= MAX_AMOUNT_OF_DL_MESSAGES){
            return blobMessages;
        } 
        else {
            return blobMessages.slice(0, MAX_AMOUNT_OF_DL_MESSAGES);
        }
    } 
    else {  
        return parsedBlob;
    } 
}

module.exports = async function (context, AlertlogicDLBlobTimer) {
    const dlblob = new AlAzureDlBlob(context, processBlob);
    
    try {
        const result = await dlblob.processDlBlobs(AlertlogicDLBlobTimer);
        invocations.logInvocationResult(context.executionContext.functionName, true);
        
        const processingErrors = result
            .filter((item) => item.status === 'rejected')
            .map((item) => ({ error: item.reason }));
        
        if (processingErrors.length > 0) {
            invocations.logInvocationResult(context.executionContext.functionName, false);
            context.log.error('DLBlob processing errors:', processingErrors);
            throw processingErrors;
        }

        context.log.info('DLBlob processing OK');
    } catch (error) {
        invocations.logInvocationResult(context.executionContext.functionName, false);
        context.log.error('DLBlob error:', error);
        throw error;
    }
};
