version: 1.0
service_name: ehub-collector

stages:
    -
        name: PR Test
        when:
            - pull_request
            - pull_request:
                trigger_phrase: test it
        image: node:18
        compute_size: small
        commands:
            - make test
    -
        name: V1 Push - Coverage
        when:
            - push: ['v1']
        image: node:18
        compute_size: small
        commands:
            - make test
            - git clone git@algithub.pd.alertlogic.net:alertlogic/al-ps-tools.git
            - cp coverage/cobertura-coverage.xml ehub-collector.coverage.xml
            - bash ./al-ps-tools/helpers/collect.sh -c 'ehub-collector.coverage.xml'
            - rm -rf ./al-ps-tools/
            - echo done
        outputs:
            file: ./.ps_outputs/*     
